name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build application
        run: echo 'No build needed for FastAPI'

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            set -e

            REPO_PATH="/Volumes/DatenAP/Code/artrack-api"
            DEPLOY_PATH="/var/www/api-artrack.arkturian.com"
            BACKUP_DIR="/var/backups"
            BACKUP_PREFIX="artrack-api"
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            BACKUP_PATH="$BACKUP_DIR/${BACKUP_PREFIX}-${TIMESTAMP}"

            cd "$REPO_PATH"

            git fetch origin main
            git reset --hard origin/main

            /root/.pyenv/versions/3.11.9/bin/pip install -r requirements.txt

            if [ -d "$DEPLOY_PATH" ]; then
              echo "Creating backup..."
              mkdir -p "$BACKUP_DIR"
              cp -r "$DEPLOY_PATH" "$BACKUP_PATH"
            fi

            echo "Deploying FastAPI application..."
            mkdir -p "$DEPLOY_PATH"
            rsync -av --delete \
              --exclude='.git' \
              --exclude='__pycache__' \
              --exclude='*.pyc' \
              --exclude='.env' \
              --exclude='venv' \
              "$REPO_PATH/" "$DEPLOY_PATH/"

            chown -R www-data:www-data "$DEPLOY_PATH"
            chmod -R 755 "$DEPLOY_PATH"

            echo "Restarting artrack-api service..."
            systemctl restart artrack-api

            echo "Deployment completed successfully!"
            echo "Backup saved to: $BACKUP_PATH"

      - name: Notify on success
        if: success()
        run: echo "✅ Deployment successful for commit ${{ github.sha }}"

      - name: Notify on failure
        if: failure()
        run: echo "❌ Deployment failed for commit ${{ github.sha }}"
